### ISSUE TITLE
Disable arriving aircraft (or make them taxi to gate)

### ISSUE THREAD

**Issue by togfoxy** [felix-b/atc#201] opened 2020-10-01 10:48 UTC
As much as I get a giggle, the planes going on a picnic kill the immersion. Arriving aircraft should be disabled until either:
a) the land and despawn or
b) can taxi to the gate.

**Comment by felix-b** [comment] 2020-10-08 19:48
Duplicate of #208. I close this one and we'll track progress on #208.

**Closed by felix-b** 2020-10-08 19:48 UTC
Labels: bug, duplicate
